version: '3.8'

name: "lcl_dev"

services:
  postgres:
    image: postgres
    ports:
     - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
     - 'postgres_data:/var/lib/postgresql/data'
  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
volumes:
  postgres_data:
